In [3]:
import numpy as np
import pandas as pd

1. ¿Qué diferencia hay entre una Serie y un DataFrame? una es unidimensional y otra bidimensional
2. Momento de trabajar con Series. Contestad a las siguientes preguntas:
Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana


In [20]:
valores1 = np.random.randint (0,10, 7)
valores1

array([8, 2, 9, 4, 6, 1, 8])

In [17]:
valores= pd.Series (valores1)
valores

0    4
1    9
2    4
3    9
4    4
5    2
6    3
dtype: int64

In [22]:
indices1= ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']
indices= pd.Series (indices1)
indices

0        lunes
1       martes
2    miercoles
3       jueves
4      viernes
5       sabado
6      domingo
dtype: object

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [30]:
serie_1= pd.Series (valores1, indices)
serie_1

lunes        8
martes       2
miercoles    9
jueves       4
viernes      6
sabado       1
domingo      8
dtype: int64

In [35]:
diccionario = dict(zip(indices, valores1))
diccionario

{'lunes': 8,
 'martes': 2,
 'miercoles': 9,
 'jueves': 4,
 'viernes': 6,
 'sabado': 1,
 'domingo': 8}

In [38]:
diccionario_s=  pd.Series(diccionario)
diccionario_s

lunes        8
martes       2
miercoles    9
jueves       4
viernes      6
sabado       1
domingo      8
dtype: int64

In [39]:
diccionario_s.shape

(7,)

In [40]:
diccionario_s.dtype

dtype('int64')

In [41]:
diccionario_s.size

7

In [42]:
diccionario_s.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [43]:
diccionario_s.values

array([8, 2, 9, 4, 6, 1, 8])

In [46]:
diccionario_s['lunes']

8

In [47]:
diccionario_s['lunes': 'miercoles']

lunes        8
martes       2
miercoles    9
dtype: int64

In [49]:
diccionario_s[['lunes','domingo']]

lunes      8
domingo    8
dtype: int64

3. Es el turno de los DataFrames

In [5]:
array3= np.random.randint (10,50, (4,3))
array3

array([[19, 18, 17],
       [23, 43, 15],
       [16, 27, 44],
       [44, 28, 28]])

In [9]:
paises= pd.DataFrame (array3, columns= ['España', 'Francia', 'Italia'])
paises

España  Francia  Italia
0      19       18      17
1      23       43      15
2      16       27      44
3      44       28      28

In [11]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

- Usando el loc extraed todas las columnas de la fila.
- Usando el loc extraed todas las columnas de China e Irán.
- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.


In [28]:
df.loc [['China', 'Irán'], :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [31]:
df.loc [['China', 'Irán'], ['Oro', 'Plata', 'Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

- Usando el iloc extraed la información de la India. Devolved todas las columnas.
- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [34]:
df.iloc [[1::2]]


SyntaxError: invalid syntax (1896899855.py, line 1)