In [2]:
import numpy as np
import pandas as pd

1. ¿Qué diferencia hay entre una Serie y un DataFrame? una es unidimensional y otra bidimensional
2. Momento de trabajar con Series. Contestad a las siguientes preguntas:
Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana


In [3]:
valores1 = np.random.randint (0,10, 7)
valores1

array([6, 3, 1, 6, 6, 8, 3])

In [4]:
valores= pd.Series (valores1)
valores

0    6
1    3
2    1
3    6
4    6
5    8
6    3
dtype: int64

In [5]:
indices1= ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']
indices= pd.Series (indices1)
indices

0        lunes
1       martes
2    miercoles
3       jueves
4      viernes
5       sabado
6      domingo
dtype: object

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [6]:
serie_1= pd.Series (valores1, indices)
serie_1

lunes        6
martes       3
miercoles    1
jueves       6
viernes      6
sabado       8
domingo      3
dtype: int64

A partir de las dos listas anteriores cread un diccionario usando un bucle for. Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. Más informción sobre este método aquí.

In [7]:
diccionario = dict(zip(indices, valores1))
diccionario

{'lunes': 6,
 'martes': 3,
 'miercoles': 1,
 'jueves': 6,
 'viernes': 6,
 'sabado': 8,
 'domingo': 3}

In [8]:
diccionario_s=  pd.Series(diccionario)
diccionario_s

lunes        6
martes       3
miercoles    1
jueves       6
viernes      6
sabado       8
domingo      3
dtype: int64

In [9]:
diccionario_s.shape

(7,)

In [10]:
diccionario_s.dtype

dtype('int64')

In [11]:
diccionario_s.size

7

In [12]:
diccionario_s.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [13]:
diccionario_s.values

array([6, 3, 1, 6, 6, 8, 3])

In [14]:
diccionario_s['lunes']

6

In [15]:
diccionario_s['lunes': 'miercoles']

lunes        6
martes       3
miercoles    1
dtype: int64

In [16]:
diccionario_s[['lunes','domingo']]

lunes      6
domingo    3
dtype: int64

3. Es el turno de los DataFrames
    - Cread un array de dos dimensiones con 4 filas y 3 columnas.

In [17]:
array3= np.random.randint (10,50, (4,3))
array3

array([[31, 12, 18],
       [18, 13, 17],
       [14, 18, 18],
       [37, 49, 47]])

In [18]:
paises= pd.DataFrame (array3, columns= ['España', 'Francia', 'Italia'])
paises

España  Francia  Italia
0      31       12      18
1      18       13      17
2      14       18      18
3      37       49      47

In [19]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

- Usando el loc extraed todas las columnas de la fila.
- Usando el loc extraed todas las columnas de China e Irán.
- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.


In [20]:
df.loc [['Tailandia'], :]

Unnamed: 0  Oro  Plata  Bronce
País                                     
Tailandia           7  132    175     278

In [21]:
df.loc [['China', 'Irán'], :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [22]:
df.loc [['China', 'Irán'], ['Oro', 'Plata', 'Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

- Usando el iloc extraed la información de la India. Devolved todas las columnas.
- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [23]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df


Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

In [24]:
df.iloc[[5],]


Unnamed: 0  Oro  Plata  Bronce
País                                 
India           6  154    202     315

In [25]:
df.iloc[1: :2, :]

Unnamed: 0   Oro  Plata  Bronce
País                                            
Japón                     2  1032   1037     985
Irán                      4   179    181     197
India                     6   154    202     315
Indonesia                 8   112    131     240
Corea del Norte          10    91    120     235

In [26]:
df.iloc[1: :2, 1:]

Oro  Plata  Bronce
País                                
Japón            1032   1037     985
Irán              179    181     197
India             154    202     315
Indonesia         112    131     240
Corea del Norte    91    120     235

Contestad a las siguientes preguntas:
- ¿Qué país consiguió más de 200 medallas de oro?
- ¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?
- ¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

In [27]:
df.loc [df.Oro>200]

Unnamed: 0   Oro  Plata  Bronce
País                                          
China                   1  1473    994     720
Japón                   2  1032   1037     985
Corea del Sur           3   745    663     827

In [28]:
df.loc [(df.Oro>200) & (df.Plata>1000)]

Unnamed: 0   Oro  Plata  Bronce
País                                  
Japón           2  1032   1037     985

In [29]:
df.loc [(df.Oro>200) | (df.Bronce>70)]

Unnamed: 0   Oro  Plata  Bronce
País                                            
China                     1  1473    994     720
Japón                     2  1032   1037     985
Corea del Sur             3   745    663     827
Irán                      4   179    181     197
Kazajistán                5   155    158     224
India                     6   154    202     315
Tailandia                 7   132    175     278
Indonesia                 8   112    131     240
China Taipéi              9    99    144     276
Corea del Norte          10    91    120     235

- Como vemos hay una columna que se llama Unnamed: 0 que no nos interesa. Eliminad esa columna.


In [30]:
df.drop(['Unnamed: 0'], axis=1)

Oro  Plata  Bronce
País                                
China            1473    994     720
Japón            1032   1037     985
Corea del Sur     745    663     827
Irán              179    181     197
Kazajistán        155    158     224
India             154    202     315
Tailandia         132    175     278
Indonesia         112    131     240
China Taipéi       99    144     276
Corea del Norte    91    120     235

- Cread una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

In [31]:
df['suma_medallas']=(df['Oro']+df['Plata']+df['Bronce'])
df.head()

Unnamed: 0   Oro  Plata  Bronce  suma_medallas
País                                                         
China                   1  1473    994     720           3187
Japón                   2  1032   1037     985           3054
Corea del Sur           3   745    663     827           2235
Irán                    4   179    181     197            557
Kazajistán              5   155    158     224            537