In [2]:
import numpy as np
import pandas as pd

1. ¿Qué diferencia hay entre una Serie y un DataFrame? una es unidimensional y otra bidimensional
2. Momento de trabajar con Series. Contestad a las siguientes preguntas:
Crea dos listas:
Una que se llame "valores" que tenga 7 números aleatorios.
Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana


In [22]:
valores1 = np.random.randint (0,10, 7)
valores1

array([0, 1, 0, 0, 2, 4, 7])

In [23]:
valores= pd.Series (valores1)
valores

0    0
1    1
2    0
3    0
4    2
5    4
6    7
dtype: int64

In [24]:
indices1= ['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo']
indices= pd.Series (indices1)
indices

0        lunes
1       martes
2    miercoles
3       jueves
4      viernes
5       sabado
6      domingo
dtype: object

A partir de estas dos listas cread una Serie donde la variable "valores" sean los valores de la Serie y la variable indices sean los índices de la Serie.

In [26]:
serie_1= pd.Series (valores1, indices)
serie_1

lunes        0
martes       1
miercoles    0
jueves       0
viernes      2
sabado       4
domingo      7
dtype: int64

In [27]:
diccionario = dict(zip(indices, valores1))
diccionario

{'lunes': 0,
 'martes': 1,
 'miercoles': 0,
 'jueves': 0,
 'viernes': 2,
 'sabado': 4,
 'domingo': 7}

In [28]:
diccionario_s=  pd.Series(diccionario)
diccionario_s

lunes        0
martes       1
miercoles    0
jueves       0
viernes      2
sabado       4
domingo      7
dtype: int64

In [29]:
diccionario_s.shape

(7,)

In [30]:
diccionario_s.dtype

dtype('int64')

In [31]:
diccionario_s.size

7

In [32]:
diccionario_s.index

Index(['lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado',
       'domingo'],
      dtype='object')

In [33]:
diccionario_s.values

array([0, 1, 0, 0, 2, 4, 7])

In [34]:
diccionario_s['lunes']

0

In [35]:
diccionario_s['lunes': 'miercoles']

lunes        0
martes       1
miercoles    0
dtype: int64

In [36]:
diccionario_s[['lunes','domingo']]

lunes      0
domingo    7
dtype: int64

3. Es el turno de los DataFrames

In [37]:
array3= np.random.randint (10,50, (4,3))
array3

array([[23, 43, 28],
       [15, 23, 24],
       [43, 16, 17],
       [44, 11, 28]])

In [38]:
paises= pd.DataFrame (array3, columns= ['España', 'Francia', 'Italia'])
paises

España  Francia  Italia
0      23       43      28
1      15       23      24
2      43       16      17
3      44       11      28

In [3]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df

FileNotFoundError: [Errno 2] No such file or directory: 'medallas.csv'

- Usando el loc extraed todas las columnas de la fila.
- Usando el loc extraed todas las columnas de China e Irán.
- Usando el loc extraed solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.


In [ ]:
df.loc [['China', 'Irán'], :]

Unnamed: 0   Oro  Plata  Bronce
País                                  
China           1  1473    994     720
Irán            4   179    181     197

In [ ]:
df.loc [['China', 'Irán'], ['Oro', 'Plata', 'Bronce']]

Oro  Plata  Bronce
País                      
China  1473    994     720
Irán    179    181     197

- Usando el iloc extraed la información de la India. Devolved todas las columnas.
- Usando el iloc extraed todas las columnas de los paises que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.
- Utilizando el código del ejercicio anterior, seleccionad unicamente las columnas "Oro", "Plata" y "Bronce".

In [4]:
df = pd.read_csv("medallas.csv", index_col=["País"])
df


FileNotFoundError: [Errno 2] No such file or directory: 'medallas.csv'

In [ ]:
df.iloc [[1::2]]


SyntaxError: invalid syntax (1896899855.py, line 1)