1. Cread tres arrays: de una, dos y tres dimensiones.
Lo podéis hacer usando los métodos de random que hemos aprendido o a través de listas em algunos casos.
📌 Nota
El array de 2 dimensiones debe ser de 2 filas y 3 columnas
El array de 3 dimensiones debe ser de 2 matrices, 3 filas y 5 columnas

In [2]:
import numpy as np

In [10]:
array1 = np.random.randint (0,100, 2)
array1

array([78, 52])

In [14]:
array2 = np.random.randint (0,100, (2,3))
array2

array([[ 9, 83, 60],
       [58, 49, 91]])

In [16]:
array3 = np.random.randint (0,100, (2,3,5))
array3

array([[[88,  0, 28,  1, 47],
        [50, 16, 93, 33, 41],
        [ 5,  6, 34, 68, 48]],

       [[87, 55, 64, 16,  8],
        [79, 77, 60, 49, 31],
        [29, 45, 26,  1, 83]]])

Chequed las las propiedades básicas de cada array que os hayáis creado. Usad en una función que nos devuelva las propiedades de una array que le pasemos.

In [26]:
def propiedades_array (i):
    print (i.shape, i.size, i.ndim, i.dtype)

In [28]:
propiedades_array (array1)

(2,) 2 1 int64


3. Cread una matriz identidad de dos dimensiones de 3 filas y 3 columnas

In [32]:
array_identidad = np.identity(3)
array_identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Cread una matriz de tres dimensiones de unos igual a la martiz de tres dimensiones creada en el primer ejercicio.

In [56]:
ones = np.ones_like(array3)
ones

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [36]:
#hacemos un array con el metodo rand porque con el anterior metodo nos salia el 'ones_like'
array3_1= np.random.rand (2,3,5)
array3_1

array([[[0.31469957, 0.25381107, 0.85885337, 0.99630227, 0.59323407],
        [0.89005229, 0.31747466, 0.91380739, 0.90160911, 0.90294407],
        [0.74021238, 0.13925328, 0.42602357, 0.57302008, 0.00714341]],

       [[0.68054286, 0.54952584, 0.00500436, 0.52067114, 0.60008417],
        [0.34237933, 0.3947386 , 0.35173648, 0.16331971, 0.51836774],
        [0.83197173, 0.23497386, 0.90315931, 0.63399792, 0.47818823]]])

In [39]:
ones2 = np.ones_like(array3_1)
ones2

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

5. ¿Se puede sumar el array de dos dimensiones que creamos en el primer ejecicios a la matriz identidad? ¿Por qué?
En caso de que no se puedan sumar, busca una solución para sumar una matriz identidad a otra. La solución puede ser crear un array nuevo.
    - Multiplicad la matriz identidad por la nueva matriz que os creasteis en el ejercicio anterior.
    - Dividid las dos matricess

In [40]:
np.add(array2, array_identidad) #no se pueden sumar por que tienen distinta forma, tienen distinto numero de filas

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [44]:
array_identidad



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
array_nuevo = np.random.randint (0,100, (3,3))
array_nuevo

array([[39, 26, 64],
       [16, 50, 66],
       [15, 92, 60]])

In [49]:
array_nuevo + array_identidad

array([[40., 26., 64.],
       [16., 51., 66.],
       [15., 92., 61.]])

In [51]:
array_nuevo * array_identidad
np.multiply (array_nuevo, array_identidad)

array([[39.,  0.,  0.],
       [ 0., 50.,  0.],
       [ 0.,  0., 60.]])

In [54]:
array_nuevo / array_identidad


/tmp/ipykernel_307/1379187484.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_nuevo / array_identidad


array([[39., inf, inf],
       [inf, 50., inf],
       [inf, inf, 60.]])

In [55]:
np.divide (array_nuevo, array_identidad)

/tmp/ipykernel_307/1037094631.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide (array_nuevo, array_identidad)


array([[39., inf, inf],
       [inf, 50., inf],
       [inf, inf, 60.]])