1-4. cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:
Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.
Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.
Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [3]:
import numpy as np

In [4]:

array1= np.round ((np.random.rand (2,3,5)), decimals=1)
array1


array([[[0.6, 0.8, 0.7, 0.6, 0.8],
        [0. , 0.6, 0.9, 1. , 0.4],
        [0.1, 0.1, 0.1, 0.7, 0.5]],

       [[0.5, 0.3, 0.1, 0.7, 0.5],
        [0.3, 0.7, 1. , 0.1, 0.5],
        [0.9, 0.7, 0.6, 0.1, 0.1]]])

In [5]:
#media = np.mean (array1)
media= np.round ((np.mean(array1)), decimals=1)
media

0.5

In [6]:
maximo = np.max (array1)
maximo2 = np.round (maximo, decimals=1)
maximo2

1.0

In [7]:
minimo= np.round ((np.min (array1)), decimals=1)
minimo

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [8]:
array1

array([[[0.6, 0.8, 0.7, 0.6, 0.8],
        [0. , 0.6, 0.9, 1. , 0.4],
        [0.1, 0.1, 0.1, 0.7, 0.5]],

       [[0.5, 0.3, 0.1, 0.7, 0.5],
        [0.3, 0.7, 1. , 0.1, 0.5],
        [0.9, 0.7, 0.6, 0.1, 0.1]]])

In [9]:
vacio= np.empty_like (array1)
vacio

array([[[0.6, 0.8, 0.7, 0.6, 0.8],
        [0. , 0.6, 0.9, 1. , 0.4],
        [0.1, 0.1, 0.1, 0.7, 0.5]],

       [[0.5, 0.3, 0.1, 0.7, 0.5],
        [0.3, 0.7, 1. , 0.1, 0.5],
        [0.9, 0.7, 0.6, 0.1, 0.1]]])

In [10]:
media= np.mean (array1).round(decimals=1)
print(media)
max= np.max(array1)
print(max)
min=np.min(array1)
print(min)

0.5
1.0
0.0


In [11]:
vacio=np.where(array1 == media, 'A', vacio) #en este primer paso ademas de sustituir los valores por A, convierte todos los numeros en strings
vacio=np.where (array1>media, 'B', vacio)
vacio=np.where (array1<media, 'C', vacio)
vacio=np.where (array1==max, 'D', vacio)
vacio=np.where (array1<min, 'E', vacio)
vacio
##se podria usar inplance=true 

array([[['B', 'B', 'B', 'B', 'B'],
        ['C', 'B', 'B', 'D', 'C'],
        ['C', 'C', 'C', 'B', 'A']],

       [['A', 'C', 'C', 'B', 'A'],
        ['C', 'B', 'D', 'C', 'A'],
        ['B', 'B', 'B', 'C', 'C']]], dtype='<U32')

In [13]:
for x in range(0,2):
    for y in range(0,3):
        for z in range(0,5):
                    
            if array1[x][y][z]== np.mean (array1):
                    vacio[x][y][z]="A"
                
            elif array1[x][y][z] > np.mean(array1):
                    vacio[x][y][z]="B"

                
            elif array1[x][y][z]< np.mean(array1):
                    vacio[x][y][z]="C"
                
            elif array1[x][y][z]== np.max (array1):
                    vacio[x][y][z]="D"
                                
            elif array1[x][y][z]== np.min (array1):
                    vacio[x][y][z]="E"
print(vacio)

[[['B' 'B' 'B' 'B' 'B']
  ['C' 'B' 'B' 'B' 'C']
  ['C' 'C' 'C' 'B' 'B']]

 [['B' 'C' 'C' 'B' 'B']
  ['C' 'B' 'B' 'C' 'B']
  ['B' 'B' 'B' 'C' 'C']]]


6. Ahora realizaremos un ejercicio similar al anterior, pero en este caso nos crearemos un array vacío unidimensional de 30 elementos. Al final de este ejercicio acabaremos teniendo un array de tres dimensiones con la misma forma que el primero que nos creamos.
En este caso:
- Si el valor del array creado en el ejercicio anterior es "A" o "B" lo reemplazaremos por 1
- Si el valor del array creado en el ejercicio anterior es "C" o "D" lo reemplazaremos por 2
- Si el valor del array creado en el ejercicio anterior es "E" lo reemplazaremos por 3.
Una vez que hayas reemplazado todos los valores cambiad la forma del array para que sea de tres dimensiones, con 2 matrices, 3 filas y 5 columnas.

In [14]:
vacio

array([[['B', 'B', 'B', 'B', 'B'],
        ['C', 'B', 'B', 'B', 'C'],
        ['C', 'C', 'C', 'B', 'B']],

       [['B', 'C', 'C', 'B', 'B'],
        ['C', 'B', 'B', 'C', 'B'],
        ['B', 'B', 'B', 'C', 'C']]], dtype='<U32')

In [15]:
array30= np.empty (30) #creamos un nuevo array de 30 elementos
array30

array([0.6, 0.8, 0.7, 0.6, 0.8, 0. , 0.6, 0.9, 1. , 0.4, 0.1, 0.1, 0.1,
       0.7, 0.5, 0.5, 0.3, 0.1, 0.7, 0.5, 0.3, 0.7, 1. , 0.1, 0.5, 0.9,
       0.7, 0.6, 0.1, 0.1])

In [17]:
vacio2=vacio.reshape(30) #para poder hacer el bucle convertimos a las mismas dimensiones que el array30
vacio2

array(['B', 'B', 'B', 'B', 'B', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C',
       'B', 'B', 'B', 'C', 'C', 'B', 'B', 'C', 'B', 'B', 'C', 'B', 'B',
       'B', 'B', 'C', 'C'], dtype='<U32')

In [19]:
for x in range (0,30):
    if vacio2 [x] == "A":
        array30 [x] = 1
    elif vacio2[x] == "B":
        array30 [x] = 1
    elif vacio2 [x] == "C":
        array30 [x] = 2
    elif vacio2 [x] == "D":
        array30 [x] = 2
    elif vacio2 [x] == "E":
        array30 [x] = 3
array30

array([1., 1., 1., 1., 1., 2., 1., 1., 1., 2., 2., 2., 2., 1., 1., 1., 2.,
       2., 1., 1., 2., 1., 1., 2., 1., 1., 1., 1., 2., 2.])

In [21]:
array_final=array30.reshape(2,3,5) #convertimos el resultado a un array de dimensiones 2,3,5
array_final

array([[[1., 1., 1., 1., 1.],
        [2., 1., 1., 1., 2.],
        [2., 2., 2., 1., 1.]],

       [[1., 2., 2., 1., 1.],
        [2., 1., 1., 2., 1.],
        [1., 1., 1., 2., 2.]]])