1-4. cread un array de tres dimensiones de 2 matrices, 3 filas y 5 columnas cuyos valores solo tengan 1 decimales. Sobre el array creado anteriormente, extraed:
Calculad la media del array y almacenarlos en una variable. Redondead a un decimal.
Calculad el valor máximo del array y almacenarlos en una variable. Redondead a un decimal.
Calculad el valor mínimo del array y almacenarlos en una variable. Redondead a un decimal.

In [12]:
import numpy as np

In [11]:

array1= np.round ((np.random.rand (2,3,5)), decimals=1)
array1


array([[[0.6, 0.9, 0.9, 0.1, 0.3],
        [0.5, 0.5, 0.3, 0.3, 0.8],
        [0.2, 0.3, 0.5, 0.8, 0.4]],

       [[0.6, 0. , 0.1, 0.2, 0.9],
        [0.6, 1. , 0.8, 0.1, 0.5],
        [0.1, 0.5, 0.9, 0.3, 0.8]]])

In [18]:
#media = np.mean (array1)
media= np.round ((np.mean(array1)), decimals=1)
media

0.5

In [20]:
maximo = np.max (array1)
maximo2 = np.round (maximo, decimals=1)
maximo2

1.0

In [22]:
minimo= np.round ((np.min (array1)), decimals=1)
minimo

0.0

5. Cread un array vacío con la misma forma y dimensiones que el array creado anteriormente.
Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:
Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

In [26]:
array1

array([[[0.6, 0.9, 0.9, 0.1, 0.3],
        [0.5, 0.5, 0.3, 0.3, 0.8],
        [0.2, 0.3, 0.5, 0.8, 0.4]],

       [[0.6, 0. , 0.1, 0.2, 0.9],
        [0.6, 1. , 0.8, 0.1, 0.5],
        [0.1, 0.5, 0.9, 0.3, 0.8]]])

In [24]:
vacio= np.empty_like (array1)
vacio

array([[[0.58456368, 0.85166362, 0.88573211, 0.07143815, 0.30966586],
        [0.54999694, 0.54203693, 0.30538229, 0.28354826, 0.79906533],
        [0.23385329, 0.26658341, 0.47246585, 0.79625464, 0.39726426]],

       [[0.56712312, 0.02088509, 0.11149309, 0.2346865 , 0.88344665],
        [0.60778251, 0.95750117, 0.79463634, 0.12004505, 0.50759802],
        [0.07037472, 0.46125507, 0.91957748, 0.30088084, 0.76979233]]])

In [29]:
np.mean (array1)


0.4933333333333334

In [34]:
np.where(array1 > 0.4)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 4, 2, 3, 0, 4, 0, 1, 2, 4, 1, 2, 4], dtype=int64))

In [43]:
for i in array1:
    for num in i:
        if num == np.mean (array1):



            #vacio [(np.where (num == np.mean (array1))] = ['A']
                       
           # vacio[[][i][num]] = ['A']
        

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (2964154578.py, line 4)

In [25]:
np.shape (array1)

(2, 3, 5)