In [3]:
import numpy as np


1. Cómo podemos crear dos arrays de dos dimensiones usando el método random_sample que tengan los mismos valores?

In [4]:
np.random.seed(1)
array1= np.random.sample(2)
array2=np.random.sample(2)
array1


array([0.417022  , 0.72032449])

In [5]:
array2

array([1.14374817e-04, 3.02332573e-01])

2- Cread los siguientes arrays:

-Un array de tres dimensiones con distribución uniforme de 2 x 3 x 5, con números entre 0 y 10, que no tengan decimales y extrae sus valores únicos almacenándolos en una variable.
-Un array de tres dimensiones con distribución binomial de 2 x 3 x 5, con probabilidad de 0.3 y número de pruebas igual a 10. Igual que antes, extrae sus valores únicos y guarda los datos en una variable.

In [6]:
array3 = np.random.randint (0,10, (2,3,5))
unicos3= np.unique (array3)
unicos3


array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [7]:
array4=np.random.binomial(10, 0.3, size = (2, 3,5))
unicos4=np.unique(array4)
unicos4

array([0, 1, 2, 3, 4, 5, 6])

3. Usando los arrays de elementos únicos obtenidos en el ejercicio anterior realizad las siguientes operaciones:
- Elementos comunes entre los dos arrays
- Unión de los dos arrays
- ¿Qué elementos están en el array derivado de la distribución uniforme y no en los únicos de la distribución binomial? Extrae los valores númericos
⚠️ Explicar cada uno de los outputs que os salgan. Que significa cada una de estas operaciones que hemos ido extrayendo?

In [8]:
np.intersect1d(unicos3, unicos4)

array([0, 1, 2, 4, 5, 6])

In [9]:
np.union1d(unicos3, unicos4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.setdiff1d (unicos3, unicos4)
#devuelve los elementos que estan en el array 1 (unicos3)y no en el array 2 (unicos4)

array([7, 8, 9])

4. Cread dos arrays usando el método random.randint de Numpy con 80 elementos cada uno con números del 1-100, con los siguientes nombres array1 y array2.
- Extraed los valores únicos de cada uno de los arrays y los guardáis en variables en las que se les llame array1 y array2.
- Identificad los elementos presentes en el array1 pero no en el array2 y asiganarlo a una variable que se llame array3.

In [11]:
array1= np.random.randint (1, 100, (80))
array1

array([93, 75, 63, 47, 33, 89, 24, 56, 66, 78,  4,  1, 78,  7, 53, 86, 71,
        3, 77, 92, 22, 76,  8, 78, 73, 76, 77, 44, 21, 31, 37,  8, 46, 69,
       58, 83, 97, 14, 11, 24, 82,  8, 25, 75, 93, 21, 33, 13, 66, 95, 61,
       25, 83, 98,  3, 93, 99, 11, 55, 97, 83, 87, 71, 67, 72, 49, 55, 16,
        6, 18, 43, 21, 49, 23, 14, 98, 54, 85, 11, 97])

In [12]:
array2= np.random.randint (1, 100, (80))
array2

array([56, 62, 57, 90, 22, 97, 84, 26, 15, 14, 85, 44,  7, 78, 57, 60, 16,
       25, 10, 67, 72, 54, 70, 37, 22, 41, 78, 92, 50, 48, 78, 41, 79, 46,
       88, 17, 29, 46, 68, 67, 79, 47,  1, 30, 64, 76, 36, 54, 94, 34,  3,
       85, 84, 49, 55, 33, 29, 56, 83, 32, 29, 95, 75,  9, 33,  9, 85, 78,
       51, 80, 42, 65, 84, 25, 21, 45, 16, 31, 92, 15])

In [13]:
array1 = np.unique (array1)
array2= np.unique (array2)

In [14]:
array3= np.setdiff1d (array1, array2)
array3

array([ 4,  6,  8, 11, 13, 18, 23, 24, 43, 53, 58, 61, 63, 66, 69, 71, 73,
       77, 82, 86, 87, 89, 93, 98, 99])

- Identificad los elementos presentes en el array2 pero no en el array1 y asiganarlo a una variable que se llame array4.

In [15]:
array4 = np.setdiff1d (array2, array1)
array4

array([ 9, 10, 15, 17, 26, 29, 30, 32, 34, 36, 41, 42, 45, 48, 50, 51, 57,
       60, 62, 64, 65, 68, 70, 79, 80, 84, 88, 90, 94])

- Identificad los elementos presentes en ambos arrays y asiganarlos a una variable que se llame array5.

In [16]:
array5= np.intersect1d (array1, array2)
array5

array([ 1,  3,  7, 14, 16, 21, 22, 25, 31, 33, 37, 44, 46, 47, 49, 54, 55,
       56, 67, 72, 75, 76, 78, 83, 85, 92, 95, 97])

- ¿Cuál es la relación que existe entre todos estos arrays? 💡 Pista 💡 Tendréis que usar las longitudes de cada uno de los arrays creados.

In [18]:
array1.size, array2.size, array3.size, array4.size, array5.size

(53, 57, 25, 29, 28)

In [26]:
array3.size+array5.size == array1.size

True