In [2]:
import numpy as np

In [3]:
# 1 Cread un array de dos dimensiones de 5 filas y 3 columnas. Sobre el array creado anteriormente, extraed:
a1 = np.random.rand(5,3)
a1

array([[0.83945108, 0.68398866, 0.19940361],
       [0.84704224, 0.48422453, 0.09772948],
       [0.13138101, 0.04166321, 0.05289521],
       [0.46832952, 0.03345557, 0.93431135],
       [0.15451836, 0.08431471, 0.49971968]])

In [4]:
# El valor de la primera fila y la segunda columna.
a1[0, 1]

0.6839886597229964

In [5]:
# Los valores de la segunda fila y las dos primeras columnas.
a1[1,:2]

array([0.84704224, 0.48422453])

In [6]:
#  Extraed las filas pares (incluyendo la 0) y todas las columnas.
a1[0::2]

array([[0.83945108, 0.68398866, 0.19940361],
       [0.13138101, 0.04166321, 0.05289521],
       [0.15451836, 0.08431471, 0.49971968]])

In [7]:
# Extraed los valores que sean mayores que 0.5.
a1[a1>0.5]

array([0.83945108, 0.68398866, 0.84704224, 0.93431135])

In [8]:
# Extraed los valores menores que 0.2 o mayores que 0.5   
a1[(a1<0.2) | (a1>0.5)]

array([0.83945108, 0.68398866, 0.19940361, 0.84704224, 0.09772948,
       0.13138101, 0.04166321, 0.05289521, 0.03345557, 0.93431135,
       0.15451836, 0.08431471])

In [9]:
# 2 Cread dos array de tres dimensiones:
# El primero de 2 matrices, 5 filas y 3 columnas.
# El segundo de 3 matrices, 2 filas y 5 columnas

a2 = np.random.randint(0,20,(2,5,3))
a3 = np.random.randint(0,20,(3,2,5))

In [10]:
# Haced un análisis exploratorio de los array creados. Recordad que en el ejercicio de ayer nos creamos una 
# función para esto.
        
def propiedades_array (i):
    print (i.shape, i.size, i.ndim, i.dtype)
        

In [11]:
propiedades_array (a2)

(2, 5, 3) 30 3 int64


In [12]:
propiedades_array (a3)

(3, 2, 5) 30 3 int64


In [13]:
# Sumad los dos arrays. ¿Podéis? ¿Por qué?

        # no se puede por distintos nº de matriz

In [14]:
# Para cambiar la forma de un array y poder hacer operaciones entre arrays que tienen distintas formas hemos 
# aprendido dos métodos:
        # .reshape()
        #.transpose()
        
a2.reshape(3,2,5)

array([[[10,  8,  8,  4, 19],
        [14, 18,  5,  2, 18]],

       [[19, 11,  0, 18, 14],
        [18,  0,  5,  9, 17]],

       [[ 9,  6,  8,  3, 11],
        [ 2,  9, 17,  7,  2]]])

In [15]:
#.transpose()

# a2 = np.random.randint(0,20,(2,5,3))
# a3 = np.random.randint(0,20,(3,2,5))

a4 =np.transpose(a2, (2,0,1))

In [16]:
# y hacer operaciones entre ellos

a_suma = (a4 + a3)
a_suma

array([[[29,  8, 27, 20, 14],
        [21, 13, 14, 17, 26]],

       [[ 9, 28, 12, 31, 23],
        [13, 36, 20,  8, 15]],

       [[12, 23, 11, 30, 30],
        [23, 27,  7, 27,  6]]])

In [17]:
# suma alter.
np.add(a4,a3)

array([[[29,  8, 27, 20, 14],
        [21, 13, 14, 17, 26]],

       [[ 9, 28, 12, 31, 23],
        [13, 36, 20,  8, 15]],

       [[12, 23, 11, 30, 30],
        [23, 27,  7, 27,  6]]])